version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart:  always
    volumes:
      - ./mongo:/data/db


  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      mongo :
          condition: service_healthy
    ports:
      - 8081:8081